// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ilpaka/landmark_app/backend/auth-service/internal/modules/auth/ports (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_store.go -package=mocks github.com/ilpaka/landmark_app/backend/auth-service/internal/modules/auth/ports Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	domain "github.com/ilpaka/landmark_app/backend/auth-service/internal/modules/auth/domain"
	ports "github.com/ilpaka/landmark_app/backend/auth-service/internal/modules/auth/ports"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CancelPendingResets mocks base method.
func (m *MockStore) CancelPendingResets(ctx context.Context, tx pgx.Tx, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelPendingResets", ctx, tx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelPendingResets indicates an expected call of CancelPendingResets.
func (mr *MockStoreMockRecorder) CancelPendingResets(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPendingResets", reflect.TypeOf((*MockStore)(nil).CancelPendingResets), ctx, tx, userID)
}

// CancelPendingVerifications mocks base method.
func (m *MockStore) CancelPendingVerifications(ctx context.Context, tx pgx.Tx, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelPendingVerifications", ctx, tx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelPendingVerifications indicates an expected call of CancelPendingVerifications.
func (mr *MockStoreMockRecorder) CancelPendingVerifications(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPendingVerifications", reflect.TypeOf((*MockStore)(nil).CancelPendingVerifications), ctx, tx, userID)
}

// ClearBlocked mocks base method.
func (m *MockStore) ClearBlocked(ctx context.Context, tx pgx.Tx, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearBlocked", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearBlocked indicates an expected call of ClearBlocked.
func (mr *MockStoreMockRecorder) ClearBlocked(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearBlocked", reflect.TypeOf((*MockStore)(nil).ClearBlocked), ctx, tx, id)
}

// GetAccountByEmailNorm mocks base method.
func (m *MockStore) GetAccountByEmailNorm(ctx context.Context, tx pgx.Tx, emailNorm string) (*ports.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByEmailNorm", ctx, tx, emailNorm)
	ret0, _ := ret[0].(*ports.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByEmailNorm indicates an expected call of GetAccountByEmailNorm.
func (mr *MockStoreMockRecorder) GetAccountByEmailNorm(ctx, tx, emailNorm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByEmailNorm", reflect.TypeOf((*MockStore)(nil).GetAccountByEmailNorm), ctx, tx, emailNorm)
}

// GetAccountByID mocks base method.
func (m *MockStore) GetAccountByID(ctx context.Context, tx pgx.Tx, id uuid.UUID) (*ports.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByID", ctx, tx, id)
	ret0, _ := ret[0].(*ports.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByID indicates an expected call of GetAccountByID.
func (mr *MockStoreMockRecorder) GetAccountByID(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByID", reflect.TypeOf((*MockStore)(nil).GetAccountByID), ctx, tx, id)
}

// GetAccountByPhoneE164 mocks base method.
func (m *MockStore) GetAccountByPhoneE164(ctx context.Context, tx pgx.Tx, phoneE164 string) (*ports.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByPhoneE164", ctx, tx, phoneE164)
	ret0, _ := ret[0].(*ports.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByPhoneE164 indicates an expected call of GetAccountByPhoneE164.
func (mr *MockStoreMockRecorder) GetAccountByPhoneE164(ctx, tx, phoneE164 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByPhoneE164", reflect.TypeOf((*MockStore)(nil).GetAccountByPhoneE164), ctx, tx, phoneE164)
}

// GetCredential mocks base method.
func (m *MockStore) GetCredential(ctx context.Context, tx pgx.Tx, userID uuid.UUID) (*ports.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredential", ctx, tx, userID)
	ret0, _ := ret[0].(*ports.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredential indicates an expected call of GetCredential.
func (mr *MockStoreMockRecorder) GetCredential(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredential", reflect.TypeOf((*MockStore)(nil).GetCredential), ctx, tx, userID)
}

// GetPasswordResetByIDForUpdate mocks base method.
func (m *MockStore) GetPasswordResetByIDForUpdate(ctx context.Context, tx pgx.Tx, id uuid.UUID) (*ports.PasswordReset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswordResetByIDForUpdate", ctx, tx, id)
	ret0, _ := ret[0].(*ports.PasswordReset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswordResetByIDForUpdate indicates an expected call of GetPasswordResetByIDForUpdate.
func (mr *MockStoreMockRecorder) GetPasswordResetByIDForUpdate(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordResetByIDForUpdate", reflect.TypeOf((*MockStore)(nil).GetPasswordResetByIDForUpdate), ctx, tx, id)
}

// GetSessionByID mocks base method.
func (m *MockStore) GetSessionByID(ctx context.Context, tx pgx.Tx, id uuid.UUID) (*ports.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByID", ctx, tx, id)
	ret0, _ := ret[0].(*ports.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByID indicates an expected call of GetSessionByID.
func (mr *MockStoreMockRecorder) GetSessionByID(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByID", reflect.TypeOf((*MockStore)(nil).GetSessionByID), ctx, tx, id)
}

// GetSessionByRefreshHashForUpdate mocks base method.
func (m *MockStore) GetSessionByRefreshHashForUpdate(ctx context.Context, tx pgx.Tx, hash string) (*ports.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByRefreshHashForUpdate", ctx, tx, hash)
	ret0, _ := ret[0].(*ports.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByRefreshHashForUpdate indicates an expected call of GetSessionByRefreshHashForUpdate.
func (mr *MockStoreMockRecorder) GetSessionByRefreshHashForUpdate(ctx, tx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByRefreshHashForUpdate", reflect.TypeOf((*MockStore)(nil).GetSessionByRefreshHashForUpdate), ctx, tx, hash)
}

// GetVerificationByIDForUpdate mocks base method.
func (m *MockStore) GetVerificationByIDForUpdate(ctx context.Context, tx pgx.Tx, id uuid.UUID) (*ports.EmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerificationByIDForUpdate", ctx, tx, id)
	ret0, _ := ret[0].(*ports.EmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerificationByIDForUpdate indicates an expected call of GetVerificationByIDForUpdate.
func (mr *MockStoreMockRecorder) GetVerificationByIDForUpdate(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerificationByIDForUpdate", reflect.TypeOf((*MockStore)(nil).GetVerificationByIDForUpdate), ctx, tx, id)
}

// IncrementPasswordResetAttempt mocks base method.
func (m *MockStore) IncrementPasswordResetAttempt(ctx context.Context, tx pgx.Tx, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementPasswordResetAttempt", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementPasswordResetAttempt indicates an expected call of IncrementPasswordResetAttempt.
func (mr *MockStoreMockRecorder) IncrementPasswordResetAttempt(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementPasswordResetAttempt", reflect.TypeOf((*MockStore)(nil).IncrementPasswordResetAttempt), ctx, tx, id)
}

// IncrementVerificationAttempt mocks base method.
func (m *MockStore) IncrementVerificationAttempt(ctx context.Context, tx pgx.Tx, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementVerificationAttempt", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementVerificationAttempt indicates an expected call of IncrementVerificationAttempt.
func (mr *MockStoreMockRecorder) IncrementVerificationAttempt(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementVerificationAttempt", reflect.TypeOf((*MockStore)(nil).IncrementVerificationAttempt), ctx, tx, id)
}

// InsertAccount mocks base method.
func (m *MockStore) InsertAccount(ctx context.Context, tx pgx.Tx, email, emailNorm string, status domain.AccountStatus, role domain.Role) (*ports.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAccount", ctx, tx, email, emailNorm, status, role)
	ret0, _ := ret[0].(*ports.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertAccount indicates an expected call of InsertAccount.
func (mr *MockStoreMockRecorder) InsertAccount(ctx, tx, email, emailNorm, status, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAccount", reflect.TypeOf((*MockStore)(nil).InsertAccount), ctx, tx, email, emailNorm, status, role)
}

// InsertAccountPhone mocks base method.
func (m *MockStore) InsertAccountPhone(ctx context.Context, tx pgx.Tx, phoneE164 string, status domain.AccountStatus, role domain.Role) (*ports.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAccountPhone", ctx, tx, phoneE164, status, role)
	ret0, _ := ret[0].(*ports.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertAccountPhone indicates an expected call of InsertAccountPhone.
func (mr *MockStoreMockRecorder) InsertAccountPhone(ctx, tx, phoneE164, status, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAccountPhone", reflect.TypeOf((*MockStore)(nil).InsertAccountPhone), ctx, tx, phoneE164, status, role)
}

// InsertAudit mocks base method.
func (m *MockStore) InsertAudit(ctx context.Context, tx pgx.Tx, e ports.AuditEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAudit", ctx, tx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAudit indicates an expected call of InsertAudit.
func (mr *MockStoreMockRecorder) InsertAudit(ctx, tx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAudit", reflect.TypeOf((*MockStore)(nil).InsertAudit), ctx, tx, e)
}

// InsertOutbox mocks base method.
func (m_2 *MockStore) InsertOutbox(ctx context.Context, tx pgx.Tx, m ports.OutboxMessage) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "InsertOutbox", ctx, tx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOutbox indicates an expected call of InsertOutbox.
func (mr *MockStoreMockRecorder) InsertOutbox(ctx, tx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOutbox", reflect.TypeOf((*MockStore)(nil).InsertOutbox), ctx, tx, m)
}

// InsertPasswordReset mocks base method.
func (m *MockStore) InsertPasswordReset(ctx context.Context, tx pgx.Tx, userID uuid.UUID, email string, salt []byte, codeHash string, expires time.Time) (*ports.PasswordReset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPasswordReset", ctx, tx, userID, email, salt, codeHash, expires)
	ret0, _ := ret[0].(*ports.PasswordReset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPasswordReset indicates an expected call of InsertPasswordReset.
func (mr *MockStoreMockRecorder) InsertPasswordReset(ctx, tx, userID, email, salt, codeHash, expires any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPasswordReset", reflect.TypeOf((*MockStore)(nil).InsertPasswordReset), ctx, tx, userID, email, salt, codeHash, expires)
}

// InsertSession mocks base method.
func (m *MockStore) InsertSession(ctx context.Context, tx pgx.Tx, s ports.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSession", ctx, tx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSession indicates an expected call of InsertSession.
func (mr *MockStoreMockRecorder) InsertSession(ctx, tx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSession", reflect.TypeOf((*MockStore)(nil).InsertSession), ctx, tx, s)
}

// InsertVerification mocks base method.
func (m *MockStore) InsertVerification(ctx context.Context, tx pgx.Tx, userID uuid.UUID, email string, salt []byte, codeHash string, expires time.Time) (*ports.EmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertVerification", ctx, tx, userID, email, salt, codeHash, expires)
	ret0, _ := ret[0].(*ports.EmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertVerification indicates an expected call of InsertVerification.
func (mr *MockStoreMockRecorder) InsertVerification(ctx, tx, userID, email, salt, codeHash, expires any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertVerification", reflect.TypeOf((*MockStore)(nil).InsertVerification), ctx, tx, userID, email, salt, codeHash, expires)
}

// ListAuditByUser mocks base method.
func (m *MockStore) ListAuditByUser(ctx context.Context, tx pgx.Tx, userID uuid.UUID, limit, offset int) ([]ports.AuditEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuditByUser", ctx, tx, userID, limit, offset)
	ret0, _ := ret[0].([]ports.AuditEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAuditByUser indicates an expected call of ListAuditByUser.
func (mr *MockStoreMockRecorder) ListAuditByUser(ctx, tx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuditByUser", reflect.TypeOf((*MockStore)(nil).ListAuditByUser), ctx, tx, userID, limit, offset)
}

// ListSessionsByUser mocks base method.
func (m *MockStore) ListSessionsByUser(ctx context.Context, tx pgx.Tx, userID uuid.UUID) ([]ports.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessionsByUser", ctx, tx, userID)
	ret0, _ := ret[0].([]ports.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessionsByUser indicates an expected call of ListSessionsByUser.
func (mr *MockStoreMockRecorder) ListSessionsByUser(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessionsByUser", reflect.TypeOf((*MockStore)(nil).ListSessionsByUser), ctx, tx, userID)
}

// ListUnpublishedOutbox mocks base method.
func (m *MockStore) ListUnpublishedOutbox(ctx context.Context, tx pgx.Tx, limit int) ([]ports.OutboxRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnpublishedOutbox", ctx, tx, limit)
	ret0, _ := ret[0].([]ports.OutboxRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnpublishedOutbox indicates an expected call of ListUnpublishedOutbox.
func (mr *MockStoreMockRecorder) ListUnpublishedOutbox(ctx, tx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnpublishedOutbox", reflect.TypeOf((*MockStore)(nil).ListUnpublishedOutbox), ctx, tx, limit)
}

// MarkAccountPhoneVerified mocks base method.
func (m *MockStore) MarkAccountPhoneVerified(ctx context.Context, tx pgx.Tx, id uuid.UUID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAccountPhoneVerified", ctx, tx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAccountPhoneVerified indicates an expected call of MarkAccountPhoneVerified.
func (mr *MockStoreMockRecorder) MarkAccountPhoneVerified(ctx, tx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAccountPhoneVerified", reflect.TypeOf((*MockStore)(nil).MarkAccountPhoneVerified), ctx, tx, id, at)
}

// MarkOutboxPublished mocks base method.
func (m *MockStore) MarkOutboxPublished(ctx context.Context, tx pgx.Tx, id int64, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOutboxPublished", ctx, tx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkOutboxPublished indicates an expected call of MarkOutboxPublished.
func (mr *MockStoreMockRecorder) MarkOutboxPublished(ctx, tx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOutboxPublished", reflect.TypeOf((*MockStore)(nil).MarkOutboxPublished), ctx, tx, id, at)
}

// MarkPasswordResetUsed mocks base method.
func (m *MockStore) MarkPasswordResetUsed(ctx context.Context, tx pgx.Tx, id uuid.UUID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPasswordResetUsed", ctx, tx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPasswordResetUsed indicates an expected call of MarkPasswordResetUsed.
func (mr *MockStoreMockRecorder) MarkPasswordResetUsed(ctx, tx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPasswordResetUsed", reflect.TypeOf((*MockStore)(nil).MarkPasswordResetUsed), ctx, tx, id, at)
}

// MarkVerificationVerified mocks base method.
func (m *MockStore) MarkVerificationVerified(ctx context.Context, tx pgx.Tx, id uuid.UUID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkVerificationVerified", ctx, tx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkVerificationVerified indicates an expected call of MarkVerificationVerified.
func (mr *MockStoreMockRecorder) MarkVerificationVerified(ctx, tx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkVerificationVerified", reflect.TypeOf((*MockStore)(nil).MarkVerificationVerified), ctx, tx, id, at)
}

// ResetCredentialFailures mocks base method.
func (m *MockStore) ResetCredentialFailures(ctx context.Context, tx pgx.Tx, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetCredentialFailures", ctx, tx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetCredentialFailures indicates an expected call of ResetCredentialFailures.
func (mr *MockStoreMockRecorder) ResetCredentialFailures(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetCredentialFailures", reflect.TypeOf((*MockStore)(nil).ResetCredentialFailures), ctx, tx, userID)
}

// RevokeAllSessionsForUser mocks base method.
func (m *MockStore) RevokeAllSessionsForUser(ctx context.Context, tx pgx.Tx, userID uuid.UUID, reason string, at time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllSessionsForUser", ctx, tx, userID, reason, at)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeAllSessionsForUser indicates an expected call of RevokeAllSessionsForUser.
func (mr *MockStoreMockRecorder) RevokeAllSessionsForUser(ctx, tx, userID, reason, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllSessionsForUser", reflect.TypeOf((*MockStore)(nil).RevokeAllSessionsForUser), ctx, tx, userID, reason, at)
}

// RevokeSession mocks base method.
func (m *MockStore) RevokeSession(ctx context.Context, tx pgx.Tx, id uuid.UUID, reason string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", ctx, tx, id, reason, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockStoreMockRecorder) RevokeSession(ctx, tx, id, reason, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockStore)(nil).RevokeSession), ctx, tx, id, reason, at)
}

// RevokeSessionAsRotation mocks base method.
func (m *MockStore) RevokeSessionAsRotation(ctx context.Context, tx pgx.Tx, oldID, newID uuid.UUID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionAsRotation", ctx, tx, oldID, newID, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSessionAsRotation indicates an expected call of RevokeSessionAsRotation.
func (mr *MockStoreMockRecorder) RevokeSessionAsRotation(ctx, tx, oldID, newID, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionAsRotation", reflect.TypeOf((*MockStore)(nil).RevokeSessionAsRotation), ctx, tx, oldID, newID, at)
}

// RevokeSessionFamily mocks base method.
func (m *MockStore) RevokeSessionFamily(ctx context.Context, tx pgx.Tx, familyID uuid.UUID, reason string, at time.Time, compromised *time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionFamily", ctx, tx, familyID, reason, at, compromised)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeSessionFamily indicates an expected call of RevokeSessionFamily.
func (mr *MockStoreMockRecorder) RevokeSessionFamily(ctx, tx, familyID, reason, at, compromised any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionFamily", reflect.TypeOf((*MockStore)(nil).RevokeSessionFamily), ctx, tx, familyID, reason, at, compromised)
}

// SetAccountPendingEmail mocks base method.
func (m *MockStore) SetAccountPendingEmail(ctx context.Context, tx pgx.Tx, id uuid.UUID, email, emailNorm string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAccountPendingEmail", ctx, tx, id, email, emailNorm)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAccountPendingEmail indicates an expected call of SetAccountPendingEmail.
func (mr *MockStoreMockRecorder) SetAccountPendingEmail(ctx, tx, id, email, emailNorm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAccountPendingEmail", reflect.TypeOf((*MockStore)(nil).SetAccountPendingEmail), ctx, tx, id, email, emailNorm)
}

// SetBlocked mocks base method.
func (m *MockStore) SetBlocked(ctx context.Context, tx pgx.Tx, id uuid.UUID, reason string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBlocked", ctx, tx, id, reason, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBlocked indicates an expected call of SetBlocked.
func (mr *MockStoreMockRecorder) SetBlocked(ctx, tx, id, reason, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBlocked", reflect.TypeOf((*MockStore)(nil).SetBlocked), ctx, tx, id, reason, at)
}

// SetEmailVerified mocks base method.
func (m *MockStore) SetEmailVerified(ctx context.Context, tx pgx.Tx, id uuid.UUID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEmailVerified", ctx, tx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEmailVerified indicates an expected call of SetEmailVerified.
func (mr *MockStoreMockRecorder) SetEmailVerified(ctx, tx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEmailVerified", reflect.TypeOf((*MockStore)(nil).SetEmailVerified), ctx, tx, id, at)
}

// SoftDeleteAccount mocks base method.
func (m *MockStore) SoftDeleteAccount(ctx context.Context, tx pgx.Tx, id uuid.UUID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteAccount", ctx, tx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteAccount indicates an expected call of SoftDeleteAccount.
func (mr *MockStoreMockRecorder) SoftDeleteAccount(ctx, tx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteAccount", reflect.TypeOf((*MockStore)(nil).SoftDeleteAccount), ctx, tx, id, at)
}

// UpdateAccountStatus mocks base method.
func (m *MockStore) UpdateAccountStatus(ctx context.Context, tx pgx.Tx, id uuid.UUID, status domain.AccountStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountStatus", ctx, tx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccountStatus indicates an expected call of UpdateAccountStatus.
func (mr *MockStoreMockRecorder) UpdateAccountStatus(ctx, tx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountStatus", reflect.TypeOf((*MockStore)(nil).UpdateAccountStatus), ctx, tx, id, status)
}

// UpdateCredentialFailures mocks base method.
func (m *MockStore) UpdateCredentialFailures(ctx context.Context, tx pgx.Tx, userID uuid.UUID, count int, lastFail *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCredentialFailures", ctx, tx, userID, count, lastFail)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCredentialFailures indicates an expected call of UpdateCredentialFailures.
func (mr *MockStoreMockRecorder) UpdateCredentialFailures(ctx, tx, userID, count, lastFail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCredentialFailures", reflect.TypeOf((*MockStore)(nil).UpdateCredentialFailures), ctx, tx, userID, count, lastFail)
}

// UpdateLastLogin mocks base method.
func (m *MockStore) UpdateLastLogin(ctx context.Context, tx pgx.Tx, id uuid.UUID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLogin", ctx, tx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLogin indicates an expected call of UpdateLastLogin.
func (mr *MockStoreMockRecorder) UpdateLastLogin(ctx, tx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLogin", reflect.TypeOf((*MockStore)(nil).UpdateLastLogin), ctx, tx, id, at)
}

// UpdatePasswordHash mocks base method.
func (m *MockStore) UpdatePasswordHash(ctx context.Context, tx pgx.Tx, userID uuid.UUID, passwordHash string, algo int16, changedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordHash", ctx, tx, userID, passwordHash, algo, changedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePasswordHash indicates an expected call of UpdatePasswordHash.
func (mr *MockStoreMockRecorder) UpdatePasswordHash(ctx, tx, userID, passwordHash, algo, changedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordHash", reflect.TypeOf((*MockStore)(nil).UpdatePasswordHash), ctx, tx, userID, passwordHash, algo, changedAt)
}

// UpsertCredential mocks base method.
func (m *MockStore) UpsertCredential(ctx context.Context, tx pgx.Tx, userID uuid.UUID, passwordHash string, algo int16) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCredential", ctx, tx, userID, passwordHash, algo)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCredential indicates an expected call of UpsertCredential.
func (mr *MockStoreMockRecorder) UpsertCredential(ctx, tx, userID, passwordHash, algo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCredential", reflect.TypeOf((*MockStore)(nil).UpsertCredential), ctx, tx, userID, passwordHash, algo)
}

// WithTx mocks base method.
func (m *MockStore) WithTx(ctx context.Context, fn func(context.Context, pgx.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockStoreMockRecorder) WithTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockStore)(nil).WithTx), ctx, fn)
}
